<?xml version="1.0"?>
  <!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED>

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName, Res, DVer?, TSet?, TInst?, RunType?, DT?, Step*, Action+, DIter*, Action*, Summary?, NodeArgs?)> 
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,NodeArgs) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
> <Report ver="2.0" tmZone="中国标准时间">
<General productName="Vugen" productVer="11" os="" host="LIUYL-PC"><DocLocation><![CDATA[F:\ltzs\lr_fpsc_2ci]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[lr_fpsc_2ci]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Summary sTime="2016/3/14 - 14:47:59" eTime="2016/3/14 - 14:47:59" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[electronInvoice_102]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2016/3/14 - 14:48:02]]></Time>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[2016/3/14 - 14:48:02]]></Time>
<NodeArgs eType="General" icon="4" nRep="10" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration1\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[electronInvoice_102]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration1\t0_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2016/3/14 - 14:48:04]]></Time>
<NodeArgs eType="General" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration1\t85632323.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA["lr_xml_get_values"]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>"lr_xml_get_values" succeeded</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2016/3/14 - 14:48:04]]></Time>
<NodeArgs eType="General" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA["lr_xml_get_values"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2016/3/14 - 14:48:04]]></Time>
<NodeArgs eType="General" icon="5" nRep="13" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration1\t58704408.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[lr_output_message]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Output message</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2016/3/14 - 14:48:04]]></Time>
<NodeArgs eType="General" icon="5" nRep="14" status="Passed" >
<Disp><![CDATA[lr_output_message]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration1\t4907990.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="2016/3/14 - 14:47:59" eTime="2016/3/14 - 14:48:04" passed="5" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[lr_fpsc_2ci Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T11">
<AName><![CDATA[vuser_end]]></AName>
<Summary sTime="2016/3/14 - 14:48:04" eTime="2016/3/14 - 14:48:04" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="17" >
<Disp><![CDATA[vuser_end Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2016/3/14 - 14:47:58" eTime="2016/3/14 - 14:48:04" passed="5" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test lr_fpsc_2ci Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>